version: "3.3"

services:

  enso-darknet:
    image: dogen/enso-darknet:latest
    environment:
      - SD_VERSION=v2_1
    command: >
        bash -c "true
        && sleep infinity
        "
    volumes:
      - ./data:/enso-darknet/data
    networks:
      - default
networks:
  default:
