version: "3.3"

services:

  enso-darknet:
    image: dogen/enso-darknet:latest
    env_file:
      - ./.env
    environment:
      - SD_VERSION=v2_1
    ports:
      - "80:80"
    command: >
      bash -c "true \
      && (./sd-worker & ./enso-darknet)
      "
    volumes:
      - ./data:/enso-darknet/data
      - ./media:/enso-darknet/media
      - ./src:/enso-darknet/src
      - ./Cargo.toml:/enso-darknet/Cargo.toml
    networks:
      - default
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    expose:
      - "6379"

networks:
  default:
